"""Add added_on to Wishlist

Revision ID: ec06126a0157
Revises: 0b24d3a954b6
Create Date: 2025-11-14 15:42:17.218849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec06126a0157'
down_revision = '0b24d3a954b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_on', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_column('added_on')

    # ### end Alembic commands ###
